### ISSUE TITLE
Having trouble using

### ISSUE THREAD

**Issue by jareddarkweb** [hakluke/haktrails#11]
I cant seem to get haktrails to work 

──(jared㉿kali)-[~]
└─$ go install -v github.com/hakluke/haktrails@latest
golang.org/x/sys/internal/unsafeheader
gopkg.in/yaml.v2
golang.org/x/sys/unix
github.com/mattn/go-isatty
github.com/mattn/go-colorable
github.com/fatih/color
github.com/hakluke/haktrails
                                                                                
┌──(jared㉿kali)-[~]
└─$ cd ~/go/bin/haktrails
cd: no such file or directory: /home/jared/go/bin/haktrails

**Comment by Albonycal** [comment]
what is your `$GOPATH` ?

**Comment by jareddarkweb** [comment]
go env                                                              
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jared/.cache/go-build"
GOENV="/home/jared/.config/go/env"
GOEXE=""
GOEXPERIMENT="fieldtrack,regabiwrappers"
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jared/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jared/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/12"
GOVCS=""
GOVERSION="unknown"
GCCGO="/usr/bin/x86_64-linux-gnu-gccgo-12"
GOAMD64="v1"
AR="ar"
CC="x86_64-linux-gnu-gcc-12"
CXX="x86_64-linux-gnu-g++-12"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3522020214=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

**Comment by jareddarkweb** [comment]
└─$ echo $GOPATH
/home/jared/.go

**Comment by Albonycal** [comment]
the binary will be here:
~/.go/bin/hacktrails
