### ISSUE TITLE
Same requested results

### ISSUE THREAD

**Issue by moashxer** [hakluke/haktrails#13]
Hi, 

First of all thanks for your amazing work & contribution. :)

I've set of subdomains from different tools `subfinder`,`amass` etc

The usual usage is;
`subfinder-amass-subdomains.txt|wc -l` --> 1000 subdomains
`cat subfinder-amass-subdomains.txt | haktrails subdomains` --> 2000 subdomains 

Now the issue is, If I did use 2nd command above again with `2000 subdomains` I'll get the same 1000 subdomains from the haktrails and then the newer subdomains, this makes to reach the API quota quicker, so due to haktrails first retrieves the same data back the user might reach the API limit before getting the newer/recent subdomains.

Solution: 
This sounds tricky or not possible from haktrails end. Haktrails should not get the `subdomains.txt` data back with API usage this will fix the duplicate requested result. This will get newer subdomains which wasn't requested from API and the subdomains which not in the file. 

Thanks

**Comment by hakluke** [comment]
Hey - the data that is returned from SecurityTrails isn't recursive like that.

Rather than passing subdomains to haktrails, pass root domains.

You will get the same results, and it will save you thousands of API requests.
