### ISSUE TITLE
Subdomains are being incorrectly output.

### ISSUE THREAD

**Issue by SecGus** [hakluke/haktrails#15]
For some reason upon running `haktrails subdomains`, it's outputting the found subdomains in the following format:
${subdomain}${domain}

As can be seen below:
<img width="682" alt="Screenshot 2023-05-28 at 19 37 36" src="https://github.com/hakluke/haktrails/assets/61525295/70a37f3f-6490-4f0f-a90e-935afd74fcb4">

**Comment by SecGus** [comment]
Just seen this is being addressed in https://github.com/hakluke/haktrails/pull/14.

**Comment by hakluke** [comment]
Merged and fixed!
