### ISSUE TITLE
Associated domain lookup doesn't work?

### ISSUE THREAD

**Issue by Vulpurpureus** [hakluke/haktrails#17]
Hi, I can successfully use the tool to find subdomains, however, the option to find associated domains doesn't work, and the output is completely empty.
Any fix for that?

**Comment by hakluke** [comment]
It seems to be working fine for me - although it will return nothing if there are no associated domains.

For example:

![image](https://github.com/hakluke/haktrails/assets/13975395/e49c7399-74fa-4406-85c8-454b2d66231b)


Can you try with tesla.com, as a test?

**Comment by jpdtester01** [comment]
Hi,

i got error when iam using the haktrails 
like iam getting "Error opening config file: open /home/jpd/.config/haktools/haktrails-config.yml: no such file or directory" these type of error what will i do to solve this one?

**Comment by hakluke** [comment]
Check the readme: https://github.com/hakluke/haktrails#config-file
