### ISSUE TITLE
Subdomains output is corrupted 

### ISSUE THREAD

**Issue by obreinx** [hakluke/haktrails#18]
using the command `echo "domain.com" | haktrails subdomains` as an example would output the following results
 `ftp
dns2
support
www
dns1`
without outputting the domain for the subdomain 
as ftp.domain.com
dns.domain.com
etc..

**Comment by obreinx** [comment]
hello?

**Comment by hakluke** [comment]
Hey - this isn't happening for me. Are you using the latest version?

![image](https://github.com/hakluke/haktrails/assets/13975395/a224a67f-35af-4950-a7a2-bd54d5143a89)

This did happen once previously, SecurityTrails randomly changed the output of the subdomains for a time and then changed it back after a few days.
