### ISSUE TITLE
haktrails usage page outputs json directly

### ISSUE THREAD

**Issue by Albonycal** [hakluke/haktrails#2]
`haktrails usage` page outputs json directly.. something like `gron` could help.. 
@hakluke if you don't have time, I can do it & create a PR..
Thank You :)

**Comment by hakluke** [comment]
Hey! I'm not really concerned about this as there are only a couple of values: `allowed_monthly_usage` and `current_monthly_usage`, but I guess we could parse it for a more human readable output.

**Comment by Albonycal** [comment]
yeaa..
