### ISSUE TITLE
is there possible way to use multiple api keys

### ISSUE THREAD

**Issue by djallalzoldik** [hakluke/haktrails#20]
I wandred if the tool can use multiple api keys the idea is there is limit using Quota 50 credits, so i need when use a lot of api key to use unlimitid Quota

**Comment by hakluke** [comment]
It would be unethical of me to add this feature. If you'd like more credits, you should pay for them.

**Comment by djallalzoldik** [comment]
no is not unethical because create multiple account in security trails is ethical :)
