### ISSUE TITLE
Problems 

### ISSUE THREAD

**Issue by KingOfBugbounty** [hakluke/haktrails#3]
Hi hakluke !! how are you, my friend? am having trouble installing need something?

![image](https://user-images.githubusercontent.com/28729614/113148596-6661a100-9208-11eb-8cb7-62bc0a38dff9.png)

**Comment by Albonycal** [comment]
Why did you close this issue? Problem fixed? What was the solution then?

**Comment by bruston** [comment]
This sort of error can happen when you update your Go installation and end up with a mix of old and new files, resolving it is usually just a case of completely removing the go directory and replacing it with the new copy.

For instance, my Go installation lives in ~/opt/go so when I upgrade I rm -Rf that directory, wget the latest tarball and unpack it.

**Comment by Albonycal** [comment]
yea
