### ISSUE TITLE
multiple keys

### ISSUE THREAD

**Issue by onuncukoy-dot** [hakluke/haktrails#5]
multiple keys
key:
key:
if you are not in shape
Should be used like xxxx, xxxx

**Comment by ghoeffner** [comment]
What's the use-case for this?

**Comment by onuncukoy-dot** [comment]
haktrails-config.yml 
ı use subdomains

**Comment by ghoeffner** [comment]
Well, I understand that, but what is the use-case of having multiple API keys?

**Comment by onuncukoy-dot** [comment]
ı read this :) ....Warning: With this tool, it's very easy to burn through a lot of API credits. For example, if you have 10,000 domains in domains.txt, running cat domains.txt | haktrails subdomains will use all 10,000 credits. It's also worth noting that some functions (such as associated domains) will use multiple API requests, for example, echo "yahoo.com" | haktrails associateddomains would use about 20 API requests, because the data is paginated and yahoo.com has a lot of associated domains.

**Comment by ghoeffner** [comment]
That is right, but these functions are only available for paid accounts anyway - the right way would be to get more queries on your api key, not to get 3 paid accounts ;)

**Comment by onuncukoy-dot** [comment]
I use free keys
:)
only 3 keys
securitytrails:
  key:
  key:
  key:
can i use it as :)
or
Is only one key entered?

**Comment by ghoeffner** [comment]
That's abusing the free account that SecurityTrails currently offers. If too many people do that, SecurityTrails will most likely stop offering it at some point. I'll leave it up to @hakluke to implement it, but I doubt this feature has a use-case that makes sense 😉

**Comment by onuncukoy-dot** [comment]
ok thanks ..

**Comment by onuncukoy-dot** [comment]
ok thanks ..

**Comment by vysecurity** [comment]
> That's abusing the free account that SecurityTrails currently offers. If too many people do that, SecurityTrails will most likely stop offering it at some point. I'll leave it up to @hakluke to implement it, but I doubt this feature has a use-case that makes sense 😉

Turns out my account only has 3,000 credits :-D

**Comment by hakluke** [comment]
Hey @onuncukoy-dot  - yeah I definitely will not be implementing this as using keys in this way would be blatant abuse of SecurityTrails' free offering.
